services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/new_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  kafka-1:
    image: apache/kafka:4.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: MFdeCJ50QzycGFW8t6g3Ww
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./volumes/server-1:/tmp/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "netstat -ltn | grep :9090 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  kafka-2:
    image: apache/kafka:4.0.1
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_KRAFT_CLUSTER_ID: MFdeCJ50QzycGFW8t6g3Ww
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9090,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./volumes/server-2:/tmp/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "netstat -ltn | grep :9090 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  kafka-3:
    image: apache/kafka:4.0.1
    ports:
      - "9096:9096"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_KRAFT_CLUSTER_ID: MFdeCJ50QzycGFW8t6g3Ww
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9090,EXTERNAL://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./volumes/server-3:/tmp/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "netstat -ltn | grep :9090 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  config-service:
    build:
      context: ./config-service
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_started

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8089:8089"
    depends_on:
      discovery-service:
        condition: service_started

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      gateway-service:
        condition: service_started

  email-notification-service:
    build:
      context: .
      dockerfile: email-notification-service/Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      user-service:
        condition: service_started
